### ISSUE TITLE
Feature: map: automatically set default map location to Czech Republic

### ISSUE THREAD

**Issue by seberm** [iBobik/berubitcoin#18]
When I access the site from a VPN the map location is automatically set based on my IP geolocation (to e.g. Amsterdam). It's difficult to change the location manually in the current UI.

Would it be possible to set the default map location to Czech Republic when the IP geolocation points outside the Czech Republic?

Thanks!

**Comment by iBobik** [comment]
Is it better in #19?
https://osm-nuxt3.berubitcoin.pages.dev/

**Comment by seberm** [comment]
Hello,
yes, it seems working fine.
